### ISSUE TITLE
Can't open Power Point slides because they are protected by information rights management

### ISSUE THREAD

**Issue by RodrigoGroener** [microsoft/aitour-customizing-microsoft-copilot#12]
Can't open Power Point slides because they are protected by information rights management. Cloud you share a public PPT slide that is accyible without an microsoft internal account?

**Comment by blackgrey0010** [comment]
@Shavonna can you please work with content owners to resolve link & perm issues. 

cc @daisychaussee

**Comment by garrytrinder** [comment]
I've uploaded a new version (v2.1) of the PowerPoint deck with the correct IRM label. The aka.ms link remains the same.
